version: '3.8'
services:
  transmax-dashboard:
    build: .
    container_name: transmax-dashboard_c
    ports:
      - '8080:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
